### ISSUE TITLE
How to avoid runtime mismatch between plugins and host?

### ISSUE THREAD

**Issue by abique** [flathub/org.freedesktop.LinuxAudio.BaseExtension#14]
Hi,

Currently no proprietary plugin vendor wants to deploy plugins on flatpak/flathub because of the potential runtime mismatch.
Also believe me, this concept is unreachable to a musician who's uncomfortable with computers, but also to many plugin vendors.

So the current situation is:
- the user download from a website and installs a pre-built binary plugin in its home folder
- then he can use his plugins from a host running from flatpak

I think we have to work with the following supposition:
- plugins deployed for an older runtime will also work on the latest runtime

In the worst case, the `dlopen()` will fail with an error message; which can also happen with plugins installed in the user's home.
Also, most plugins will have a minimal dependency surface so the chances are high that this will work.

Then we don't need a 1:1 branch per runtime for plugins and we don't need to explain that to anyone.

Thank you for considering this issue,
Alex

**Comment by Bleuzen** [comment]
> plugins deployed for an older runtime will also work on the latest runtime

Usually this works pretty well. For most plugins there is no need for regular rebuilds, builds still work even after multiple years.

Also there are more benefits when getting rid of the branching.
(from my old post here: https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension/issues/5#issuecomment-986320089)
basically:
- much easier to understand
- plugins don't disappear every year (when DAWs update their runtime)
- easier to display in graphical software stores
- less disk space wasted
- faster updates
- less work for plugin package maintainers

So I would really welcome a change regarding getting rid of the branches, at least where possible.

**Comment by jpf91** [comment]
Any news on this issue? I wonder whether it makes sense to update https://github.com/flathub/fm.reaper.Reaper to use the `24.08` release, but I guess we will lose access to all old plugins then?

**Comment by hfiguiere** [comment]
Reaper is already wrong it use 24.08 but not right branch for the plugins.
This is not a bug here.

**Comment by jpf91** [comment]
@hfiguiere That's true. I just submitted a PR to update the reaper manifest to fix this.

@abique If proprietary vendors don't want recompile their binaries for newer runtimes, couldn't they just re-release the same binaries for the new branch? This has the benefit that we still could have different releases in the branches if needed. But if testing shows that a binary plugin works fine with the newer runtime, it could just be tagged for that new branch.

**Comment by abique** [comment]
@jpf91 then why not simply make a single release and say that it is compatible with multiple runtimes?

99% of the time for audio plugins they are forward compatible, so if they say compat with 20.04 they'll likely work in 22.04 and 24.04.

**Comment by hfiguiere** [comment]
nothing that can be done here.
