### ISSUE TITLE
Consider shipping libcurl-gnutls.so.4 in base extension

### ISSUE THREAD

**Issue by ghost** [flathub/org.freedesktop.LinuxAudio.BaseExtension#7]
Some VSTs for Linux don't work inside Flatpak sandbox as they require `libcurl-gnutls.so.4`. See https://github.com/flathub/com.bitwig.BitwigStudio/issues/6 for my investigation into why this is.

The simplest workaround could be to ship a `libcurl-gnutls.so` library in this extension.
VSTs with this link issue would start working out-of-the-box.

Pros:

  * Flatpak VST hosts would immediately be able to load plugins from [AudioDamage](https://www.audiodamage.com/), [Harrison Consoles](https://harrisonconsoles.com/harrison-software-downloads/) and probably more.

Cons:

  * Ongoing updates to the copy of libcurl are needed.

I don't think creating Flatpak manifests for each Audio Damage VST is feasible - there are 100s, there are not stable download links for them, and we don't necessarily have the right to redistribute them.

The ideal solution would be for Audio Damage and Harrison to rebuild all their plugins to link against `libcurl` instead of `libcurl-gnutls` - I haven't contacted either organisation about this, and I expect it wouldn't happen overnight.

**Comment by hfiguiere** [comment]
how would that work?

**Comment by hfiguiere** [comment]
nothing we can do here.

**Comment by ghost** [comment]
Agreed. I think it's also less widespread of a problem than I initially thought it was.
