### ISSUE TITLE
LV2 Path suggested in Readme breaks presets

### ISSUE THREAD

**Issue by x42** [flathub/org.freedesktop.LinuxAudio.BaseExtension#9]
The Readme suggests
```
--env=LV2_PATH=/app/extensions/Plugins/lv2"
``` 
That lacks a writable user-specific part and breaks plugin-presets. If no writable path is given, presets are saved to the default path `$HOME/.lv2`,  but afterwards they are not found by the host, unless `$HOME/.lv2` is in the `LV2_PATH`.

See  https://lv2plug.in/pages/filesystem-hierarchy-standard.html  "The user specific portion of LV2_PATH should be used for this [save data/prests]".

Please change the README to:
```
--env=LV2_PATH=/app/extensions/Plugins/lv2:$HOME/.lv2"
```

**Comment by hfiguiere** [comment]
Closed with commit 0fb3166
